# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-14
spec:
  selector:
    matchLabels:
      app: module-14
  replicas: 1
  template:
    metadata:
      labels:
        app: module-14
    spec:
      containers:
        - name: todo-app
          image: todo-app:prod
          imagePullPolicy: Never
          ports:
          - containerPort: 5000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: SECRET_KEY
                  optional: false
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: client-id
                  key: CLIENT_ID
                  optional: false
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: client-secret
                  key: CLIENT_SECRET
                  optional: false
            - name: STATE
              value: "57303239348286232875"
            - name: ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: endpoint
                  key: ENDPOINT
                  optional: false
            - name: DATABASE
              value: "mh-todoapp-2022"
            - name: LOGGLY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: loggly-token
                  key: LOGGLY_TOKEN
                  optional: false
            - name: LOG_LEVEL
              value: "INFO"
            - name: FLASK_ENV
              value: "production"
            - name: LOGIN_DISABLED
              value: "False"