version: "3.8"
services:
  todo_app:
    image: python:3.8
    build:
      context: .
      target: development
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./todo_app:/app/todo_app
    env_file: .env
