name: Continuous Integration
on: 
  push:
    paths:
      - 'README.md'
      - '.gitignore'
      - 'documentation'
  pull_request_review:
    types:
      - submitted
  schedule:
    - cron:  '30 17 * * *'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        uses: actions/checkout@v2
        run: docker build --target test --platform linux/amd64 --tag todo-app:test .
      - name: Run tests
        uses: actions/checkout@v2
        run: docker run --env-file ./.env.test todo-app:test