name: Continuous Integration
on: 
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'documentation'
  pull_request_review:
    types:
      - submitted
  schedule:
    - cron: '30 17 * * *'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files 
        uses: actions/checkout@v2
      - name: Build docker
        run: docker build --target test --platform linux/amd64 --tag todo-app:test .
      - name: Run tests
        run: docker run --env-file ./.env.test todo-app:test
  publish:
    env:
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_ACCESS_USER }}
      AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
    # if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
    name: Push to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_ACCESS_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Checkout files 
        uses: actions/checkout@v2
      - name: Build docker
        run: docker build --target production --tag $DOCKER_HUB_USER/todo-app:prod-${{ github.sha }} .
      - name: Push to docker hub
        run: docker push $DOCKER_HUB_USER/todo-app:prod-${{ github.sha }}
      - name: Re-pull and restart the app in azure
        run: curl -dH -X POST 'https://\$mh-todo-app-2022:$AZURE_PASSWORD@mh-todo-app-2022.scm.azurewebsites.net/api/registry/webhook'
    needs: build
